# -*- coding: utf-8 -*-
"""aluno6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sHNPUf08lW26Ro_Z_OSNPlMsCJpAx-sV
"""

from random import randint 
frutas = ['banana','manga','maça','uva','pera']
carros = ['bmw','porshe','fusca','celta','toyota']
pessoas = ['lucas','davi','samuel','wollas','rayane']
listadeacertos = []
listadeerros = []
categorias=randint(1,3)
print(categorias)
if categorias == 3:
    lucas = pessoas
    nSecreta = pessoas[randint(0,4)]
elif categorias == 2:
    lucas = carros
    nSecreta = carros[randint(0,4)]
else:
    nSecreta = frutas[randint(0,4)]
    lucas = frutas
print(nSecreta)
x = nSecreta.replace('','')
print(f'a categorias e {lucas} e tem {len(x)}letras')